// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TAdminStatus
{
    public byte FstatusId { get; set; }

    public string FstatusName { get; set; }

    public string Fdescription { get; set; }

    public DateTime? FcreatedAt { get; set; }

    public virtual ICollection<TAdmin> TAdmins { get; set; } = new List<TAdmin>();
}