// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TAnnounce
{
    public int FAnnounceId { get; set; }

    public string FTitle { get; set; }

    public string FContent { get; set; }

    public int FCategoryId { get; set; }

    public int FPriority { get; set; }

    public DateTime FCreatedAt { get; set; }

    public DateTime FUpdatedAt { get; set; }

    public string Status { get; set; }

    public virtual TAnnounceCategory FCategory { get; set; }
}