// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TAnnounceCategory
{
    public int FCategoryId { get; set; }

    public string FCategoryName { get; set; }

    public virtual ICollection<TAnnounce> TAnnounces { get; set; } = new List<TAnnounce>();
}