// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TChat
{
    public int FChatId { get; set; }

    public int FPosterId { get; set; }

    public int FWorkerId { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public virtual TUser FPoster { get; set; }

    public virtual TUser FWorker { get; set; }

    public virtual ICollection<TMessagesHistory> TMessagesHistories { get; set; } = new List<TMessagesHistory>();
}