// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TConfirmReply
{
    public int FconfirmReplyId { get; set; }

    public int FtaskId { get; set; }

    public int FposterId { get; set; }

    public int FworkerId { get; set; }

    public string FconfirmationType { get; set; }

    public string FconfirmationStatus { get; set; }

    public string Fremarks { get; set; }

    public virtual TPoster Fposter { get; set; }

    public virtual TTask Ftask { get; set; }

    public virtual TWorker Fworker { get; set; }
}