// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TImage
{
    public int FimageId { get; set; }

    public int FuserId { get; set; }

    public string Frole { get; set; }

    public string Fcategory { get; set; }

    public string FimageName { get; set; }

    public string FimagePath { get; set; }

    public bool? FisMain { get; set; }

    public DateTime? FcreatedAt { get; set; }

    public virtual TUser Fuser { get; set; }
}