// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TTaskFollow
{
    public int FfollowId { get; set; }

    public int FfollowerId { get; set; }

    public int FtaskId { get; set; }

    public DateTime? FcreatedAt { get; set; }

    public virtual TUser Ffollower { get; set; }

    public virtual TTask Ftask { get; set; }
}