// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackMange.Models;

public partial class TUserType
{
    public int FuserTypeId { get; set; }

    public string FuserTypeName { get; set; }

    public virtual ICollection<TUser> Fusers { get; set; } = new List<TUser>();
}